name: SSL Email Test (Outlook)

on:
  workflow_dispatch: # run manually from the Actions tab

jobs:
  test-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show repo files (debug)
        run: |
          pwd
          ls -la

      - name: Verify scripts exist (debug)
        shell: pwsh
        run: |
          $files = @("Send-SMTPAlert.ps1", "Send-ExpiryEmail.ps1")
          foreach ($file in $files) {
            if (-Not (Test-Path $file)) {
              Write-Error "Missing required script: $file"
              exit 1
            }
          }

      - name: Create test JSON with High severity
        shell: pwsh
        run: |
          $json = @(
            @{
              severity = "high"
              domain   = "example.com"
              daysLeft = 5
              expiryDate = (Get-Date).AddDays(5).ToString("yyyy-MM-dd")
            }
          ) | ConvertTo-Json -Depth 3
          $json | Out-File -FilePath test.json -Encoding utf8

      - name: Send SMTP email (Outlook)
        shell: pwsh
        run: |
          ./Send-SMTPAlert.ps1 `
            -SmtpServer "smtp.office365.com" `
            -SmtpPort 587 `
            -UseSsl `
            -From "${{ secrets.SMTP_FROM }}" `
            -To @("${{ secrets.SMTP_TO }}") `
            -Subject "Test SSL Alert - Outlook" `
            -BodyHtml "<h3>This is a test email from GitHub Actions SSL workflow using Outlook SMTP.</h3>" `
            -Username "${{ secrets.SMTP_USER }}" `
            -Password "${{ secrets.SMTP_PASS }}"
