name: SSL Email Test

on:
  workflow_dispatch:  # Allows manual run

jobs:
  test-email:
    runs-on: ubuntu-latest

    steps:
      # 1) Pull your repo files into the runner
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Create a small JSON file with "High" severity to trigger email
      - name: Create test JSON
        shell: pwsh
        run: |
          @(
            @{
              Host="example.com"; Issuer="Let's Encrypt";
              ExpiryDate=[DateTime]::UtcNow.AddDays(5).ToString("yyyy-MM-dd");
              DaysRemaining=5; Severity="High"; Owner="${{ secrets.SMTP_TO }}"
            }
          ) | ConvertTo-Json | Set-Content .\sslCertificateDetails.json
          Write-Host "Test JSON created."

      # 3) Send the email
      - name: Send SMTP email
        shell: pwsh
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          SMTP_TO: ${{ secrets.SMTP_TO }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          pwsh -File .\Send-ExpiryEmail.ps1 `
            -ResultsPath ".\sslCertificateDetails.json" `
            -EnvName "TEST" `
            -SMTP_SERVER $env:SMTP_SERVER `
            -SMTP_PORT   [int]$env:SMTP_PORT `
            -SMTP_SSL:$true `
            -SMTP_FROM   $env:SMTP_FROM `
            -SMTP_TO     $env:SMTP_TO `
            -SMTP_USER   $env:SMTP_USER `
            -SMTP_PASS   $env:SMTP_PASS
