name: SSL Email Test (Outlook)

on:
  workflow_dispatch: # run manually from the Actions tab

jobs:
  test-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show repo files (debug)
        run: |
          pwd
          ls -la

      - name: Verify scripts exist (debug)
        shell: pwsh
        run: |
          $files = @("Send-SMTPAlert.ps1","Send-ExpiryEmail.ps1")
          foreach ($file in $files) {
            if (-Not (Test-Path $file)) {
              Write-Error "Missing required file: $file"
              exit 1
            }
          }

      - name: Create test JSON with High severity
        run: |
          echo '[{"domain": "example.com", "severity": "High", "days_left": 5, "owner": "security-team@example.com"}]' > test.json

      - name: Send SMTP email (Outlook)
        shell: pwsh
        run: |
          ./Send-SMTPAlert.ps1 `
            -SmtpServer $env:SMTP_SERVER `
            -SmtpPort $env:SMTP_PORT `
            -UseSsl `
            -From $env:SMTP_FROM `
            -To $env:SMTP_TO `
            -Subject "Test SSL Email from GitHub Actions" `
            -BodyHtml "<p>This is a test email from GitHub Actions via Outlook SMTP.</p>" `
            -Username $env:SMTP_USER `
            -Password $env:SMTP_PASS
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          SMTP_TO: ${{ secrets.SMTP_TO }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
